export default {
    install(Vue) {
        require('text-contents-vue-components').default.install(Vue);
        require('description-vue-components').default.install(Vue);
        require('helper-vue-components').default.install(Vue);

        registerVueComponent(
            'grayscale-contact',
            require('./Contact/Contact/Component.vue').default,
            Vue,
			'grayscale-landing-page-vue-components/Contact/Contact/Component.vue'
        );
        registerVueComponent(
            'grayscale-contact-card',
            require('./Contact/Card/Component.vue').default,
            Vue,
			'grayscale-landing-page-vue-components/Contact/Card/Component.vue'
        );
        registerVueComponent(
            'grayscale-medium-text-content',
            require('./MediumTextContent/Component.vue').default,
            Vue,
			'grayscale-landing-page-vue-components/MediumTextContent/Component.vue'
        );
        registerVueComponent(
            'grayscale-large-text-content',
            require('./LargeTextContent/Component.vue').default,
            Vue,
			'grayscale-landing-page-vue-components/LargeTextContent/Component.vue'
        );

        registerVueComponent(
            'grayscale-about',
            require('./About/Component.vue').default,
            Vue,
			'grayscale-landing-page-vue-components/About/Component.vue'
        );
        registerVueComponent(
            'grayscale-header',
            require('./Header/Component.vue').default,
            Vue,
			'grayscale-landing-page-vue-components/Header/Component.vue'
        );
        registerVueComponent(
            'grayscale-navigation-bar',
            require('./NavigationBar/CollapsableNavigationBar/Component.vue').default,
            Vue,
			'grayscale-landing-page-vue-components/NavigationBar/CollapsableNavigationBar/Component.vue'
        );
        registerVueComponent(
            'grayscale-navigation-link',
            require('./NavigationBar/NavigationLink/Component.vue').default,
            Vue,
			'grayscale-landing-page-vue-components/NavigationBar/NavigationLink/Component.vue'
        );
        registerVueComponent(
            'grayscale-signup',
            require('./Signup/Component.vue').default,
            Vue,
			'grayscale-landing-page-vue-components/Signup/Component.vue'
        );

        registerVueComponent(
            'grayscale-landing-page',
            require('./LandingPage/Component.vue').default,
            Vue,
			'grayscale-landing-page-vue-components/LandingPage/Component.vue'
        );
    },
};
